- name: Tap homebrew taps
  community.general.homebrew_tap:
    state: present
    name:
      - aws/tap
      - mongodb/brew
      - siderolabs/tap

- name: Install homebrew packages
  community.general.homebrew:
    state: latest
    name: "{{ item }}"
  loop:
      - ansible
      - awscli
      - bash
      - bash-completion@2
      - circleci
      - coreutils
      - curl
      - gawk
      - gnu-sed
      - gnu-tar
      - goreleaser
      - grep
      - helm
      - htop
      - jq
      - just
      - kubernetes-cli
      - mysql-client
      - neovim
      - pulumi
      - ripgrep
      - shellcheck
      - shfmt
      - talosctl
      - tree-sitter
      - watch
      - yq

- name: Install homebrew casks
  when: ansible_system == "Darwin"
  community.general.homebrew_cask:
    state: latest
    name: "{{ item }}"
  loop:
      - homebrew/cask/docker
      - homebrew/cask/firefox
      - homebrew/cask/font-hack-nerd-font
      - homebrew/cask/wezterm
      - homebrew/cask/notion
      - homebrew/cask/rectangle
