#!/bin/bash

if [[ $(pwd) == *"TransactionService"* ]]; then
    exit 0
fi

if [[ $(pwd) == *"MPBX"* ]]; then
    exit 0
fi

function check_for_invalid_commits() {
    commit=$(git log -n1 --grep "$1")
    if [[ -n $commit ]]; then
        echo "Found a commit with invalid message pattern: $1"
        exit 1
    fi
}

check_for_invalid_commits "^fixup! "
check_for_invalid_commits "^squash! "
check_for_invalid_commits "^WIP: "   
check_for_invalid_commits "^wip: "   
check_for_invalid_commits "^wip "    
