---
prompt_for_commit_message: true

mappings:
  - match: '.config/nvim/snippets'
    link_as_dir: true
  - match: ".*gpg-agent.conf.darwin"
    dest: ~/.gnupg/gpg-agent.conf
    target_os: Darwin
  - match: ".config/nixos/configuration.nix"
    dest: /etc/nixos/configuration.nix
    target_os:
      - "Linux"
  - match: "playbooks/workstation"
    link_as_dir: true

modules:
  - repo: https://github.com/ohmyzsh/ohmyzsh
    link: none
    location: ~/.oh-my-zsh
    pull_only: true
  # FZF
  - repo: https://github.com/junegunn/fzf
    link: none
    location: ~/.config/fzf
    pull_only: true
    hooks:
      after_sync:
        - ./install --xdg --key-bindings --no-fish --no-update-rc --completion
  # My not-so-secret secrets
  - repository: git@github.com:chasinglogic/secrets.git
    name: secrets
