---
prompt_for_commit_message: true

mappings:
  - match: '.config/nvim/snippets'
    link_as_dir: true
  - match: ".*gpg-agent.conf.darwin"
    dest: ~/.gnupg/gpg-agent.conf
    target_os: Darwin
  - match: "Library"
    target_os:
      - "Darwin"
  - match: "README.md"
    skip: true
  - match: ".config/nixos/configuration.nix"
    dest: /etc/nixos/configuration.nix
    target_os:
      - "Linux"

hooks:
  after_link:
    - |
      if [ ! -f "$HOME/.local/bin/mise" ]; then
        echo "Installing mise"
        install-mise
      fi

modules:
  # Multiple runtime version manager
  - repo: https://github.com/asdf-vm/asdf.git
    link: none
    location: ~/.asdf
    pull_only: true
  # FZF
  - repo: https://github.com/junegunn/fzf
    link: none
    location: ~/.config/fzf
    pull_only: true
    hooks:
      after_sync:
        - ./install --xdg --key-bindings --no-zsh --no-fish --no-update-rc --completion
  # My not-so-secret secrets
  - repository: git@github.com:chasinglogic/secrets.git
    name: secrets
