---
groups_to_create:
  - name: docker
  - name: wheel
  - name: sudo

users:
  - username: chasinglogic
    name: Mathew Robinson
    home: /home/chasinglogic
    update_password: on_create
    groups:
      - sudo
      - wheel
      - docker
      - libvirt
      - kvm

zsh_users: "{{ users }}"

dconf_settings:
  - name: Set CAPSLOCK as Ctrl and Disable ALTGR on UK keyboards
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['ctrl:nocaps', 'lv3:ralt_alt']"

rpm_package_specs: []

rpm_packages:
  - awscli2
  - bash-completion
  - bind # provides dig
  - docker
  - docker-compose
  - firefox
  - git
  - htop
  - nmap
  - podman
  - podman-compose
  - snapper
  - tealdeer
  - traceroute
  - unzip
  - virt-manager
  - wl-clipboard
