[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "git" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "nix" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "ssh" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "just" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "nix" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "go" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "ssh", "sleep" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "ls" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "gcloud", "jq" ]

[[rule]]
toolName = "enter_plan_mode"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "golangci-lint" ]

[[rule]]
toolName = "replace"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "ls", "grep", "xargs" ]
