[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "poetry" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "sed", "cd", "just" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "poetry" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "nix-locate" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "find", "head" ]
allowRedirection = true
