- name: Add docker signing key
  become: true
  become_user: root
  when: ansible_distribution == 'Ubuntu'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add docker repository
  become: true
  become_user: root
  when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: |
      deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install docker
  become: true
  become_user: root
  when: ansible_distribution == 'Ubuntu'
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
