- name: Add repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: Hashicorp RPM repo
    baseurl: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo

- name: Install Terraform
  ansible.builtin.dnf:
    name: terraform
    state: installed

- name: Install Packer
  ansible.builtin.dnf:
    name: packer
    state: latest
